export const CHANGE_DATE = 'CHANGE_DATE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const LOAD_MENUS = 'LOAD_MENUS';
export const LOAD_MENUS_SUCCESS = 'LOAD_MENUS_SUCCESS';
